RegisterNetEvent('PGRP_PHONESYSTEM:Error')
AddEventHandler('PGRP_PHONESYSTEM:Error', function(errorMessage)
    SetNotificationTextEntry('STRING')
	AddTextComponentSubstringPlayerName('~r~[ERROR]~w~ ' .. errorMessage)
	DrawNotification(false, true)
end)

RegisterNetEvent('PGRP_PHONESYSTEM:MESSAGERECIEVED')
AddEventHandler('PGRP_PHONESYSTEM:MESSAGERECIEVED', function(name, message)
    SetNotificationTextEntry('STRING')
	AddTextComponentSubstringPlayerName('~o~[Phone] ~n~~w~New Message from: ~b~' .. name)
	DrawNotification(false, true)

    SetNotificationTextEntry('STRING')
    AddTextComponentSubstringPlayerName('~o~[Phone] ~n~~w~Message: ~n~~b~' .. message)
    DrawNotification(false, true)
end)

RegisterNetEvent('PGRP_PHONESYSTEM:MESSAGESENT')
AddEventHandler('PGRP_PHONESYSTEM:MESSAGESENT', function(name, message)
    SetNotificationTextEntry('STRING')
	AddTextComponentSubstringPlayerName('~o~[Phone] ~w~Message sent to: ~b~' .. name)
	DrawNotification(false, true)
end)